### ISSUE TITLE
Bootstrap breaking Add Player title

### ISSUE THREAD

**Issue by DaveeHorvath** [DaveeHorvath/ascension#34]
it removes the h1 tags vertical align, but we need it for the carousel

**Comment by madfcat** [comment]
> it removes the h1 tags vertical align, but we need it for the carousel

I think bootstrap uses something like _reboot.css, where it resets the styles.
We tried to do a custom build of bootstrap to only export the carousel.
If we only export the carousel related css and js, host it and use it instead of the whole bootstrap imported from CDN, it won't break the current layout, I guess.

Can you check this link:
https://getbootstrap.com/docs/3.4/customize/
?
