### ISSUE TITLE
on master completed game get 400 from backend from tournament and 1v1

### ISSUE THREAD

**Issue by DaveeHorvath** [DaveeHorvath/ascension#40]

**Comment by taoramo** [comment]
I'm getting this as well, will investigate tomorrow what it's about.

**Comment by madfcat** [comment]
From my understandng, the problem is in body's JSON `userIds` which has the first userId empty.

<img width="599" alt="image" src="https://github.com/user-attachments/assets/65d139dc-21b3-4aa9-9598-80975f6d3f34" />

For instance, it is even earlier:
<img width="752" alt="image" src="https://github.com/user-attachments/assets/7283004f-0768-44fa-a9ca-7b68514af701" />

The userIds are not set correctly for the game.
